#pragma once
#include"Scene/GameObjects/PlayScene/Effect/SandstormEffect.h"
class BulletManager;
class Player;
class ObjectsManager;
class TreeManager;
class AirshipManager;
class WindmillManager;
class Enemy;
class BenchManager;
class StreetLightManager;
//敵の管理者のクラスを定義する
class SandstormManager
{
public:
	//キル数のゲッター、セッター
	unsigned int GetKillCount() const { return m_killCount; }
	void SetKillCount(const unsigned int& killCount) { m_killCount = killCount; }

public:
	/// <summary>
	/// コンストラクタ
	/// </summary>
	SandstormManager();

	/// <summary>
	/// デストラクタ
	/// </summary>
	~SandstormManager();

	/// <summary>
	/// 初期化
	/// </summary>
	/// <param name="bulletManager">球のアドレス</param>
	/// <param name="player">プレイヤーのアドレス</param>
	void Intialize(
		BulletManager* bulletManager=nullptr, 
		BenchManager* benchManager=nullptr,
		StreetLightManager* streetLightManager=nullptr
	);

	/// <summary>
	/// 更新する
	/// </summary>
	/// <param name="elapsedTime">フレーム時間</param>
	void Update(const float& elapsedTime);

	/// <summary>
	/// 描画する
	/// </summary>
	void Render();

	/// <summary>
	/// 後始末
	/// </summary>
	void Finalize();

	/// <summary>
	/// プレイヤーと当たり判定
	/// </summary>
	/// <param name="player">プレイヤーのアドレス</param>
	void CheckHitCharacter(Player* player);

	/// <summary>
	/// プレイヤーと当たり判定
	/// </summary>
	/// <param name="player">プレイヤーのアドレス</param>
	void CheckHitEnemy(Enemy* enemy);

	/// <summary>
	/// 自動生成
	/// </summary>
	void AutoGenerated();

private:
	//敵の配列のポインタ
	std::vector<std::unique_ptr<SandstormEffect>> m_sandstormEffect;

	//キル数
	unsigned int m_killCount;

	//生成時間
	float m_generationTime;
};